spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
spark.sql.catalog.polaris=org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.polaris.type=rest
spark.sql.catalog.polaris.uri=http://polaris:8181/api/catalog
spark.sql.catalog.polaris.warehouse=quickstart_catalog
spark.sql.catalog.polaris.credential=root:s3cr3t
spark.sql.catalog.polaris.scope=PRINCIPAL_ROLE:ALL
spark.sql.catalog.polaris.header.X-Iceberg-Access-Delegation=vended-credentials
spark.sql.catalog.polaris.io-impl=org.apache.iceberg.aws.s3.S3FileIO
spark.sql.defaultCatalog=polaris
spark.sql.catalogImplementation=in-memory
spark.driver.host=spark-iceberg
spark.driver.bindAddress=0.0.0.0
spark.ui.enabled=true
spark.ui.port=4040
