version: '2'
services:

  notebook:
    image: "jupyter/scipy-notebook"
    ports:
      - "8888:8888"
    volumes:
      - ..:/home/jovyan/tcdm
    user: root
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - GRANT_SUDO=yes
    command: start-notebook.sh --NotebookApp.token=''
