coordinator=true
node-scheduler.include-coordinator=true
http-server.http.port=8080
discovery.uri=http://trino-hdfs:8080
query.max-memory-per-node=768MB
query.max-memory=1GB
query.max-total-memory=2GB
memory.heap-headroom-per-node=192MB
