connector.name=iceberg
iceberg.catalog.type=hive_metastore
hive.metastore.uri=thrift://hive-metastore:9083
hive.metastore.authentication.type=NONE
hive.hdfs.authentication.type=NONE
hive.hdfs.impersonation.enabled=false
fs.hadoop.enabled=true
