version: '3'
services:
  zeppelin:
    build: .
    ports:
        - "8080:8080"
        - "4040:4040"
    volumes:
        - ./logs:/logs
        - ./notebook:/notebook
        - ./datos:/datos
    environment:
        - ZEPPELIN_LOG_DIR=/logs
        - ZEPPELIN_NOTEBOOK_DIR=/notebook
