services:

  namenode:
    image: namenode-image
    container_name: namenode
    ports:
      - "9871:9870"
      - "8089:8088"
    entrypoint: ["/inicio.sh"]
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 3072m
    networks:
      hadoop-cluster-mr:
        aliases:
          - resourcemanager

  datanode1:
    image: datanode-image
    container_name: datanode1
    entrypoint: ["/inicio.sh"]
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 3072m
    networks:
      hadoop-cluster-mr:

  datanode2:
    image: datanode-image
    container_name: datanode2
    entrypoint: ["/inicio.sh"]
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 3072m
    networks:
      hadoop-cluster-mr:


networks:
  hadoop-cluster-mr:
    external: true
    name: hadoop-cluster-mr
